running: local
domain: http:localhost:8080

spring:
  h2:
    console:
      enable: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
payment:
  cid: TC0ONETIME   #가맹점 테스트 코드
  admin_key: 3c725716b1f2e3f653face8dde4fa836  #카카오 어플리케이션 어드민 키
  host: https://kapi.kakao.com/v1/payment

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ${google_client_id}
#            clientSecret: ${google_client_secret}
#            scope:
#              - email
#              - profile
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#jwt:
#  secret: ${secret_key}
#  access-token-expiration-minutes: 1800000
#  refresh-token-expiration-minutes: 604800000
